import {
  ProcurementTask,
  MaterialItem,
  RequisitionSlip,
  BorrowRecord,
  FixedAsset,
  TextbookRecord,
  AuditItem,
} from './types';

export const INITIAL_TASKS: ProcurementTask[] = [
  {
    id: 'task-1',
    type: 'purchase',
    title: 'ซื้อวัสดุอุปกรณ์จัดกิจกรรมวันสำคัญทางศาสนาและวันแม่แห่งชาติ',
    categoryName: 'วันสำคัญ',
    dateStr: '1 ต.ค. 69',
    rawDate: '2026-10-01',
    amount: 2375,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ร้านสหกรณ์การเกษตรและเครื่องเขียน',
    budgetSource: 'เงินอุดหนุนรายหัว',
    poNumber: 'บก 01/2569',
    projectId: 'proj-5',
    projectCode: 'โครงการที่ 05/2569',
    projectName: 'โครงการส่งเสริมคุณธรรม จริยธรรม และกิจกรรมวันสำคัญ',
    projectOwnerName: 'นางสาววิไลวรรณ พรหมมา',
    activityId: 'act-5-1',
    activityCode: 'กิจกรรมที่ 5.1',
    activityName: 'กิจกรรมจัดงานวันสำคัญทางศาสนา วันแม่ และวันพ่อแห่งชาติ',
    committee: ['นายสมศักดิ์ มุ่งมั่น', 'นางสาววิไลวรรณ พรหมมา', 'นายมานพ ชัยเจริญ'],
    description: 'จัดซื้อผ้าผูกประดับ ดอกไม้สด ธูปเทียน และริบบิ้นสำหรับกิจกรรมวันสำคัญ',
    items: [
      { name: 'ผ้าประดับขาว-ฟ้า', quantity: 2, unit: 'ม้วน', unitPrice: 450, total: 900 },
      { name: 'พานพุ่มประดิษฐ์', quantity: 2, unit: 'คู่', unitPrice: 500, total: 1000 },
      { name: 'ริบบิ้นและเข็มกลัดที่ระลึก', quantity: 1, unit: 'ชุด', unitPrice: 475, total: 475 },
    ],
  },
  {
    id: 'task-2',
    type: 'w804',
    title: 'ซื้อหมึกพิมพ์และกระดาษถ่ายเอกสาร A4 ปริมาณงานเร่งด่วน (ว.804)',
    categoryName: 'ว.804',
    dateStr: '28 ก.ย. 69',
    rawDate: '2026-09-28',
    amount: 3890,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ร้านปรีดาการค้า',
    budgetSource: 'เงินอุดหนุนรายหัว (ค่าจัดการเรียนการสอน)',
    poNumber: 'ว.804-09/2569',
    projectId: 'proj-1',
    projectCode: 'โครงการที่ 01/2569',
    projectName: 'โครงการพัฒนาคุณภาพผู้เรียนและยกระดับผลสัมฤทธิ์ทางการศึกษา',
    projectOwnerName: 'นายธีรพล สินธุ',
    activityId: 'act-1-1',
    activityCode: 'กิจกรรมที่ 1.1',
    activityName: 'กิจกรรมยกระดับผลสัมฤทธิ์ O-NET/NT และติวเข้มวิชาการ',
    committee: ['นางสาวรัตนา สว่างศรี'],
    description: 'จัดซื้อหมึกพิมพ์ Canon GI-790 และกระดาษถ่ายเอกสาร A4 70 แกรม จำนวน 5 รีม สำหรับพิมพ์ข้อสอบกลางภาค',
    items: [
      { name: 'หมึกพิมพ์แท้ Canon GI-790 ดำ/สี', quantity: 4, unit: 'ขวด', unitPrice: 280, total: 1120 },
      { name: 'กระดาษ Double A A4 80 แกรม', quantity: 10, unit: 'รีม', unitPrice: 145, total: 1450 },
      { name: 'แฟ้มห่วงเอกสาร 2 นิ้ว', quantity: 12, unit: 'เล่ม', unitPrice: 110, total: 1320 },
    ],
  },
  {
    id: 'task-3',
    type: 'hire',
    title: 'จ้างเหมาบริการทำความสะอาดและซ่อมบำรุงระบบระบายน้ำอาคารเรียน 1',
    categoryName: 'จ้างเหมา',
    dateStr: '25 ก.ย. 69',
    rawDate: '2026-09-25',
    amount: 4500,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'นายวิเชียร บุญยัง',
    budgetSource: 'เงินรายได้สถานศึกษา',
    poNumber: 'จบ 08/2569',
    projectId: 'proj-3',
    projectCode: 'โครงการที่ 03/2569',
    projectName: 'โครงการปรับปรุงซ่อมแซมและพัฒนาสภาพแวดล้อมอาคารสถานที่',
    projectOwnerName: 'นายสมศักดิ์ มุ่งมั่น',
    activityId: 'act-3-2',
    activityCode: 'กิจกรรมที่ 3.2',
    activityName: 'ซ่อมบำรุงระบบระบายน้ำและสุขาภิบาลรอบอาคาร 1',
    committee: ['นายประดิษฐ์ ใจงาม', 'นายธีรพล สินธุ'],
    description: 'จ้างเหมาลอกรางระบายน้ำรอบอาคารเรียน 1 และล้างบ่อพักน้ำทิ้งเตรียมรับฤดูฝน',
  },
  {
    id: 'task-4',
    type: 'w119',
    title: 'ค่าใช้จ่ายบริหารงานสำนักงาน ค่าน้ำยาล้างจาน น้ำยาทำความสะอาดห้องน้ำ (ว.119)',
    categoryName: 'ว.119',
    dateStr: '22 ก.ย. 69',
    rawDate: '2026-09-22',
    amount: 1680,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ห้างหุ้นส่วนจำกัด โลตัส ชุมชน',
    budgetSource: 'เงินอุดหนุนค่าใช้จ่ายดำเนินงาน',
    poNumber: 'ว.119-04/2569',
    projectId: 'proj-3',
    projectCode: 'โครงการที่ 03/2569',
    projectName: 'โครงการปรับปรุงซ่อมแซมและพัฒนาสภาพแวดล้อมอาคารสถานที่',
    projectOwnerName: 'นายสมศักดิ์ มุ่งมั่น',
    activityId: 'act-3-2',
    activityCode: 'กิจกรรมที่ 3.2',
    activityName: 'ซ่อมบำรุงระบบระบายน้ำและสุขาภิบาลรอบอาคาร 1',
    committee: ['นางมาลี ตั้งใจ'],
    description: 'ซื้อเวชภัณฑ์และน้ำยาทำความสะอาดสำหรับงานสุขาภิบาลโรงเรียน',
  },
  {
    id: 'task-5',
    type: 'construction',
    title: 'จ้างปรับปรุงซ่อมแซมพื้นระเบียงทางเดินและหลังคาห้องพยาบาล',
    categoryName: 'ก่อสร้าง',
    dateStr: '18 ก.ย. 69',
    rawDate: '2026-09-18',
    amount: 18500,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ช่างสมหมาย การช่าง',
    budgetSource: 'เงินรายได้สถานศึกษา',
    poNumber: 'กส 02/2569',
    projectId: 'proj-3',
    projectCode: 'โครงการที่ 03/2569',
    projectName: 'โครงการปรับปรุงซ่อมแซมและพัฒนาสภาพแวดล้อมอาคารสถานที่',
    projectOwnerName: 'นายสมศักดิ์ มุ่งมั่น',
    activityId: 'act-3-1',
    activityCode: 'กิจกรรมที่ 3.1',
    activityName: 'ซ่อมแซมพื้นระเบียงทางเดินและหลังคาห้องพยาบาล',
    committee: ['นายทัศน์พล เจริญสุข', 'นายสมเกียรติ สิทธิ', 'นางกมลวรรณ ดวงดี'],
    description: 'เปลี่ยนกระเบื้องหลังคาที่แตกร้าว 25 แผ่น และปูกระเบื้องยางกันลื่นทางลาดหน้าห้องพยาบาล',
  },
  {
    id: 'task-6',
    type: 'purchase',
    title: 'ซื้ออุปกรณ์กีฬาสำหรับกิจกรรมพลศึกษาและแข่งขันกีฬากลุ่มโรงเรียน',
    categoryName: 'งานซื้อ',
    dateStr: '15 ก.ย. 69',
    rawDate: '2026-09-15',
    amount: 12000,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ร้านสปอร์ตแลนด์',
    budgetSource: 'เงินอุดหนุนกิจกรรมพัฒนาคุณภาพผู้เรียน',
    poNumber: 'บก 02/2569',
    committee: ['นายชัยรัตน์ ชูชีพ', 'นายอนุสรณ์ มงคล', 'นางสาวจินตนา รักชาติ'],
    description: 'ลูกฟุตบอล มอลเทน 5 ลูก, ลูกวอลเลย์บอล มิกาซ่า 5 ลูก, ลูกเซปักตะกร้อ 6 ลูก, กรวยฝึกซ้อม 20 อัน',
  },
  {
    id: 'task-7',
    type: 'w804',
    title: 'ซื้อปลั๊กไฟ สายพ่วง และหลอดไฟ LED เปลี่ยนอาคารเรียนอนุบาล (ว.804)',
    categoryName: 'ว.804',
    dateStr: '10 ก.ย. 69',
    rawDate: '2026-09-10',
    amount: 2450,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ร้านสมบูรณ์การไฟฟ้า',
    budgetSource: 'เงินอุดหนุนรายหัว',
    poNumber: 'ว.804-08/2569',
    committee: ['นายทัศน์พล เจริญสุข'],
    description: 'เปลี่ยนหลอดฟลูออเรสเซนต์เดิมเป็นหลอด LED T8 ประหยัดพลังงาน 18W จำนวน 15 หลอด และสายไฟต่อพ่วง',
  },
  {
    id: 'task-8',
    type: 'hire',
    title: 'จ้างเหมาพิมพ์เอกสารรายงานผลสัมฤทธิ์และวารสารประชาสัมพันธ์โรงเรียน',
    categoryName: 'จ้างเหมา',
    dateStr: '05 ก.ย. 69',
    rawDate: '2026-09-05',
    amount: 8500,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'โรงพิมพ์เจริญกิจออฟเซ็ท',
    budgetSource: 'เงินอุดหนุนการจัดการศึกษาขั้นพื้นฐาน',
    poNumber: 'จบ 07/2569',
    committee: ['นางสาวศิริพร บุญตา', 'นายพิทักษ์ ปัญญา', 'นางชิดชนก สุขเกษม'],
    description: 'พิมพ์สมุดรายงานผลการเรียน ปพ.5 และวารสารข่าวสารนิคมสายโท 12 เหนือ ฉบับประจำภาคเรียนที่ 1/2569',
  },
  {
    id: 'task-9',
    type: 'w119',
    title: 'ค่าใช้จ่ายรับรองการตรวจเยี่ยมของคณะกรรมการนิเทศ สพป.',
    categoryName: 'ว.119',
    dateStr: '01 ก.ย. 69',
    rawDate: '2026-09-01',
    amount: 1200,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ร้านป้าแจ๋ว อาหารตามสั่ง',
    budgetSource: 'เงินรายได้สถานศึกษา',
    poNumber: 'ว.119-03/2569',
    committee: ['นายสมศักดิ์ มุ่งมั่น'],
    description: 'อาหารว่างและเครื่องดื่มต้อนรับคณะกรรมการประเมินผลการประกันคุณภาพภายในสถานศึกษา',
  },
  {
    id: 'task-10',
    type: 'purchase',
    title: 'ซื้อหนังสือเรียนตามโครงการสนับสนุนค่าใช้จ่ายการจัดการศึกษาตั้งแต่ระดับอนุบาลจนจบการศึกษาขั้นพื้นฐาน',
    categoryName: 'หนังสือเรียน',
    dateStr: '25 ส.ค. 69',
    rawDate: '2026-08-25',
    amount: 28350,
    status: 'in_progress',
    statusText: 'กำลังดำเนินการ',
    vendorName: 'องค์การค้าของ สกสค.',
    budgetSource: 'เงินเรียนฟรี 15 ปี (หมวดหนังสือเรียน)',
    poNumber: 'บก 03/2569',
    committee: ['นายทัศน์พล เจริญสุข', 'นางนันทนา สดใส', 'นางสาวนิตยา พันธุ์ไทย'],
    description: 'หนังสือเรียน 8 กลุ่มสาระการเรียนรู้ ชั้น ป.1 - ป.6 ตามหลักสูตรแกนกลาง 2551 (ฉบับปรับปรุง 2560)',
  },
  {
    id: 'task-11',
    type: 'w804',
    title: 'ซื้อแปลงผักและเมล็ดพันธุ์พืชสำหรับโครงการเกษตรเพื่ออาหารกลางวัน',
    categoryName: 'ว.804',
    dateStr: '20 ส.ค. 69',
    rawDate: '2026-08-20',
    amount: 2150,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ร้านเกษตรพัฒนา',
    budgetSource: 'เงินอุดหนุนโครงการอาหารกลางวัน',
    poNumber: 'ว.804-07/2569',
    committee: ['นายสนอง กลิ่นแก้ว'],
    description: 'ดินปลูกสำเร็จรูป ปุ๋ยหมักชีวภาพ เมล็ดผักบุ้ง คะน้า กวางตุ้ง ถั่วฝักยาว',
  },
  {
    id: 'task-12',
    type: 'construction',
    title: 'จ้างปรับปรุงทาสีห้องสมุดมีชีวิตและซ่อมชั้นวางหนังสือ',
    categoryName: 'ก่อสร้าง',
    dateStr: '15 ส.ค. 69',
    rawDate: '2026-08-15',
    amount: 9800,
    status: 'in_progress',
    statusText: 'กำลังดำเนินการ',
    vendorName: 'ช่างเอกชัย อินทร์ทอง',
    budgetSource: 'เงินพัฒนาสถานศึกษา',
    poNumber: 'กส 01/2569',
    committee: ['นางสาวรัตนา สว่างศรี', 'นายทัศน์พล เจริญสุข'],
    description: 'ทาสีภายในห้องสมุดโทนสว่าง และเสริมฐานชั้นวางหนังสือเหล็ก 4 ตัว',
  },
  {
    id: 'task-13',
    type: 'w119',
    title: 'ค่าใช้จ่ายซื้อสายแลนและหัว RJ45 ซ่อมจุดต่ออินเทอร์เน็ตห้องคอมพิวเตอร์',
    categoryName: 'ว.119',
    dateStr: '10 ส.ค. 69',
    rawDate: '2026-08-10',
    amount: 850,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ร้านไอทีคอนเน็ค',
    budgetSource: 'เงินอุดหนุนรายหัว',
    poNumber: 'ว.119-02/2569',
    committee: ['นายทัศน์พล เจริญสุข'],
    description: 'สาย UTP Cat6 1 กล่องย่อย และหัวต่อ RJ45 สำหรับซ่อมแซมจุดเชื่อมต่อเครื่องคอมพิวเตอร์นักเรียน',
  },
  {
    id: 'task-14',
    type: 'hire',
    title: 'จ้างซ่อมเครื่องปรับอากาศห้องประชุมโรงเรียน (ล้างแอร์และเติมน้ำยา R32)',
    categoryName: 'จ้างเหมา',
    dateStr: '01 ส.ค. 69',
    rawDate: '2026-08-01',
    amount: 3200,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'อุดมแอร์เซอร์วิส',
    budgetSource: 'เงินอุดหนุนรายหัว',
    poNumber: 'จบ 06/2569',
    committee: ['นายสมศักดิ์ มุ่งมั่น', 'นางสาวจินตนา รักชาติ'],
    description: 'ล้างทำความสะอาดแอร์แบบแขวน 36,000 BTU 2 เครื่อง ตรวจเช็คกระแสไฟและเติมน้ำยาทำความเย็น',
  },
  {
    id: 'task-15',
    type: 'w804',
    title: 'ซื้อชุดทดลองวิทยาศาสตร์พื้นฐานและสารเคมีสาธิตระดับประถม',
    categoryName: 'ว.804',
    dateStr: '20 ก.ค. 69',
    rawDate: '2026-07-20',
    amount: 4750,
    status: 'completed',
    statusText: 'เสร็จแล้ว',
    vendorName: 'ศึกษาภัณฑ์ศึกษาภัณฑ์พาณิชย์',
    budgetSource: 'เงินอุดหนุนกิจกรรมพัฒนาคุณภาพผู้เรียน',
    poNumber: 'ว.804-06/2569',
    committee: ['นางสาววิไลวรรณ พรหมมา'],
    description: 'หลอดทดลอง บีกเกอร์ กระดาษลิตมัส แท่งแก้วคนสาร สำหรับการทดลองวิทยาศาสตร์ ป.4-6',
  },
];

export const INITIAL_MATERIALS: MaterialItem[] = [
  {
    id: 'mat-1',
    code: 'ว-001',
    name: 'กระดาษถ่ายเอกสาร A4 80 แกรม (Double A)',
    category: 'วัสดุสำนักงาน',
    unit: 'รีม',
    balance: 42,
    minStock: 20,
    unitPrice: 145,
    lastUpdated: '1 ต.ค. 69',
  },
  {
    id: 'mat-2',
    code: 'ว-002',
    name: 'หมึกพิมพ์ Canon GI-790 Black',
    category: 'วัสดุคอมพิวเตอร์',
    unit: 'ขวด',
    balance: 6,
    minStock: 5,
    unitPrice: 280,
    lastUpdated: '28 ก.ย. 69',
  },
  {
    id: 'mat-3',
    code: 'ว-003',
    name: 'หมึกพิมพ์ Canon GI-790 Cyan/Magenta/Yellow',
    category: 'วัสดุคอมพิวเตอร์',
    unit: 'ชุด',
    balance: 3,
    minStock: 3,
    unitPrice: 840,
    lastUpdated: '28 ก.ย. 69',
  },
  {
    id: 'mat-4',
    code: 'ว-004',
    name: 'ปากกาไวท์บอร์ด น้ำเงิน/แดง/ดำ (ตราม้า)',
    category: 'วัสดุการศึกษา',
    unit: 'ด้าม',
    balance: 85,
    minStock: 30,
    unitPrice: 22,
    lastUpdated: '25 ก.ย. 69',
  },
  {
    id: 'mat-5',
    code: 'ว-005',
    name: 'แฟ้มห่วง 2 นิ้ว ตราช้าง 2100F',
    category: 'วัสดุสำนักงาน',
    unit: 'เล่ม',
    balance: 24,
    minStock: 10,
    unitPrice: 110,
    lastUpdated: '20 ก.ย. 69',
  },
  {
    id: 'mat-6',
    code: 'ว-006',
    name: 'น้ำยาทำความสะอาดพื้น มาจิคลีน 5 ลิตร',
    category: 'วัสดุงานบ้านงานครัว',
    unit: 'แกลลอน',
    balance: 8,
    minStock: 4,
    unitPrice: 240,
    lastUpdated: '22 ก.ย. 69',
  },
  {
    id: 'mat-7',
    code: 'ว-007',
    name: 'หลอดไฟ LED T8 18W ขั้ว G13 แสงขาว',
    category: 'วัสดุไฟฟ้าและวิทยุ',
    unit: 'หลอด',
    balance: 14,
    minStock: 10,
    unitPrice: 95,
    lastUpdated: '10 ก.ย. 69',
  },
  {
    id: 'mat-8',
    code: 'ว-008',
    name: 'ลวดเย็บกระดาษ No.10 Max',
    category: 'วัสดุสำนักงาน',
    unit: 'กล่อง',
    balance: 55,
    minStock: 20,
    unitPrice: 18,
    lastUpdated: '15 ก.ย. 69',
  },
];

export const INITIAL_REQUISITIONS: RequisitionSlip[] = [
  {
    id: 'req-1',
    slipNumber: 'บพ 045/2569',
    date: '1 ต.ค. 69',
    requesterName: 'ครูนันทนา สดใส',
    department: 'สายชั้นประถมศึกษาปีที่ 2',
    items: [
      { name: 'กระดาษถ่ายเอกสาร A4 80 แกรม', quantity: 3, unit: 'รีม' },
      { name: 'ปากกาไวท์บอร์ด สีน้ำเงิน', quantity: 4, unit: 'ด้าม' },
    ],
    purpose: 'ใช้พิมพ์ใบงานวิชาคณิตศาสตร์และภาษาไทยเตรียมสอบปลายภาคเรียนที่ 1',
    status: 'approved',
  },
  {
    id: 'req-2',
    slipNumber: 'บพ 046/2569',
    date: '30 ก.ย. 69',
    requesterName: 'ครูชัยรัตน์ ชูชีพ',
    department: 'กลุ่มสาระสุขศึกษาและพลศึกษา',
    items: [
      { name: 'นกหวีด Fox 40', quantity: 2, unit: 'อัน' },
      { name: 'ถ่าน AA สำหรับนาฬิกาจับเวลา', quantity: 4, unit: 'ก้อน' },
    ],
    purpose: 'ใช้ในการจัดการแข่งขันกรีฑากลุ่มเครือข่ายโรงเรียน',
    status: 'pending',
  },
  {
    id: 'req-3',
    slipNumber: 'บพ 044/2569',
    date: '27 ก.ย. 69',
    requesterName: 'ครูมาลี ตั้งใจ',
    department: 'สายชั้นปฐมวัย',
    items: [
      { name: 'กระดาษการ์ดสี A4', quantity: 2, unit: 'แพ็ค' },
      { name: 'กาวลาเท็กซ์ 16 ออนซ์', quantity: 3, unit: 'ขวด' },
      { name: 'กรรไกรปลายมนสำหรับเด็ก', quantity: 10, unit: 'เล่ม' },
    ],
    purpose: 'จัดทำสื่อการเรียนรู้พัฒนาการกล้ามเนื้อมัดเล็กเด็กอนุบาล 3',
    status: 'disbursed',
  },
];

export const INITIAL_BORROWS: BorrowRecord[] = [
  {
    id: 'borrow-1',
    code: 'ยพ-69/014',
    assetName: 'เครื่องฉายโปรเจคเตอร์ Epson EB-X06 พร้อมจอพับ 100 นิ้ว',
    borrowerName: 'นางมาลี ตั้งใจ',
    department: 'สายชั้นปฐมวัย',
    borrowDate: '20 ก.ย. 69',
    dueDate: '25 ก.ย. 69',
    status: 'overdue',
    phone: '081-987-6543',
    note: 'เกินกำหนดส่งคืน 6 วัน (ใช้จัดแสดงผลงานนิทรรศการหนูน้อยคนเก่ง)',
  },
  {
    id: 'borrow-2',
    code: 'ยพ-69/015',
    assetName: 'ลำโพงล้อลากเคลื่อนที่ไมค์ลอยคู่บลูทูธ (MBA 15 นิ้ว)',
    borrowerName: 'นายพิทักษ์ ปัญญา',
    department: 'กลุ่มงานวิชาการ',
    borrowDate: '26 ก.ย. 69',
    dueDate: '30 ก.ย. 69',
    status: 'overdue',
    phone: '089-123-4567',
    note: 'เกินกำหนดส่งคืน 1 วัน (ใช้ซ้อมดนตรีและกิจกรรมเข้าแถว)',
  },
  {
    id: 'borrow-3',
    code: 'ยพ-69/016',
    assetName: 'กล้องดิจิทัล Canon EOS 3000D พร้อมการ์ด 64GB',
    borrowerName: 'นางสาววิไลวรรณ พรหมมา',
    department: 'งานประชาสัมพันธ์โรงเรียน',
    borrowDate: '29 ก.ย. 69',
    dueDate: '5 ต.ค. 69',
    status: 'borrowed',
    phone: '086-456-7890',
    note: 'บันทึกภาพการแข่งขันฟุตบอลเยาวชน',
  },
  {
    id: 'borrow-4',
    code: 'ยพ-69/012',
    assetName: 'โน้ตบุ๊กคอมพิวเตอร์ Acer TravelMate P214 (ศธ 04052.12/66/004)',
    borrowerName: 'นายสมศักดิ์ มุ่งมั่น',
    department: 'กลุ่มบริหารทั่วไป',
    borrowDate: '10 ก.ย. 69',
    dueDate: '15 ก.ย. 69',
    returnDate: '15 ก.ย. 69',
    status: 'returned',
    phone: '084-332-1100',
    note: 'ส่งคืนเรียบร้อยในสภาพสมบูรณ์',
  },
];

export const INITIAL_ASSETS: FixedAsset[] = [
  {
    id: 'ast-1',
    assetNumber: 'ศธ 04052.12/67/001',
    name: 'เครื่องคอมพิวเตอร์ประมวลผล All-in-One Dell Inspiron',
    specs: 'Intel Core i5, RAM 16GB, SSD 512GB, จอ 23.8 นิ้ว',
    acquisitionDate: '15 พ.ค. 67',
    price: 24500,
    fundingSource: 'งบประมาณแผ่นดิน (สพป.บุรีรัมย์ เขต 2)',
    location: 'ห้องพัสดุและธุรการ',
    custodian: 'ครูทัศน์พล เจริญสุข',
    condition: 'good',
  },
  {
    id: 'ast-2',
    assetNumber: 'ศธ 04052.12/66/008',
    name: 'เครื่องมัลติฟังก์ชันเลเซอร์ Canon imageRUNNER 2206N',
    specs: 'พิมพ์/สแกน/ถ่ายเอกสาร ขาวดำ A3/A4 22 แผ่น/นาที',
    acquisitionDate: '10 ส.ค. 66',
    price: 36000,
    fundingSource: 'เงินรายได้สถานศึกษา',
    location: 'ห้องธุรการกลาง',
    custodian: 'นางสาวรัตนา สว่างศรี',
    condition: 'good',
  },
  {
    id: 'ast-3',
    assetNumber: 'ศธ 04052.12/65/012',
    name: 'เครื่องฉายโปรเจคเตอร์ Epson EB-X06',
    specs: 'ความสว่าง 3,600 ANSI Lumens, ความละเอียด XGA',
    acquisitionDate: '20 มิ.ย. 65',
    price: 15900,
    fundingSource: 'เงินอุดหนุนรายหัว',
    location: 'ห้องพัสดุ (สำหรับยืมใช้งาน)',
    custodian: 'ครูทัศน์พล เจริญสุข',
    condition: 'good',
  },
  {
    id: 'ast-4',
    assetNumber: 'ศธ 04052.12/64/005',
    name: 'เครื่องปรับอากาศแบบติดผนัง Daikin Inverter 24,000 BTU',
    specs: 'เบอร์ 5 อินเวอร์เตอร์ รุ่น FTKC28UV2S',
    acquisitionDate: '5 เม.ย. 64',
    price: 28900,
    fundingSource: 'ผ้าป่าเพื่อการศึกษา',
    location: 'ห้องสมุดมีชีวิต',
    custodian: 'นางนันทนา สดใส',
    condition: 'good',
  },
  {
    id: 'ast-5',
    assetNumber: 'ศธ 04052.12/63/019',
    name: 'โต๊ะเก้าอี้นักเรียนระดับประถมศึกษา (มอก. 1494-2541)',
    specs: 'ชุดโต๊ะเก้าอี้ไม้เนื้อแข็ง โครงเหล็กกลม 1 ชุด',
    acquisitionDate: '12 พ.ย. 63',
    price: 1450,
    fundingSource: 'งบประมาณ สพฐ.',
    location: 'ห้องเรียนชั้น ป.4',
    custodian: 'นายสมศักดิ์ มุ่งมั่น',
    condition: 'fair',
  },
];

export const INITIAL_TEXTBOOKS: TextbookRecord[] = [
  {
    id: 'tb-1',
    grade: 'ป.1',
    subject: 'ภาษาไทย (ภาษาพาที)',
    title: 'ภาษาพาที ชั้นประถมศึกษาปีที่ 1',
    publisher: 'องค์การค้าของ สกสค.',
    studentCount: 18,
    unitPrice: 52,
    totalAmount: 936,
    status: 'distributed',
  },
  {
    id: 'tb-2',
    grade: 'ป.1',
    subject: 'คณิตศาสตร์ เล่ม 1',
    title: 'คณิตศาสตร์ เล่ม 1 ชั้นประถมศึกษาปีที่ 1 (สสวท.)',
    publisher: 'สสวท. / องค์การค้า',
    studentCount: 18,
    unitPrice: 65,
    totalAmount: 1170,
    status: 'distributed',
  },
  {
    id: 'tb-3',
    grade: 'ป.2',
    subject: 'ภาษาไทย (วรรณคดีลำนำ)',
    title: 'วรรณคดีลำนำ ชั้นประถมศึกษาปีที่ 2',
    publisher: 'องค์การค้าของ สกสค.',
    studentCount: 22,
    unitPrice: 48,
    totalAmount: 1056,
    status: 'distributed',
  },
  {
    id: 'tb-4',
    grade: 'ป.3',
    subject: 'วิทยาศาสตร์และเทคโนโลยี เล่ม 1',
    title: 'วิทยาศาสตร์และเทคโนโลยี เล่ม 1 (สสวท.)',
    publisher: 'สสวท.',
    studentCount: 20,
    unitPrice: 72,
    totalAmount: 1440,
    status: 'received',
  },
  {
    id: 'tb-5',
    grade: 'ป.4',
    subject: 'สังคมศึกษา ศาสนาและวัฒนธรรม',
    title: 'สังคมศึกษา ป.4 ฉบับปรับปรุง',
    publisher: 'อักษรเจริญทัศน์ (อจท.)',
    studentCount: 25,
    unitPrice: 85,
    totalAmount: 2125,
    status: 'ordered',
  },
];

export const INITIAL_AUDIT_ITEMS: AuditItem[] = [
  {
    id: 'aud-1',
    assetNumber: 'ศธ 04052.12/67/001',
    name: 'เครื่องคอมพิวเตอร์ All-in-One Dell',
    location: 'ห้องพัสดุและธุรการ',
    auditor: 'นายธีรพล สินธุ',
    auditDate: '30 ก.ย. 69',
    status: 'verified',
    notes: 'สภาพพร้อมใช้งาน หมายเลขตรงตามทะเบียน',
  },
  {
    id: 'aud-2',
    assetNumber: 'ศธ 04052.12/66/008',
    name: 'เครื่องมัลติฟังก์ชันเลเซอร์ Canon IR2206N',
    location: 'ห้องธุรการกลาง',
    auditor: 'นายธีรพล สินธุ',
    auditDate: '30 ก.ย. 69',
    status: 'verified',
    notes: 'ใช้งานได้ดี ตลับหมึกเปลี่ยนใหม่',
  },
  {
    id: 'aud-3',
    assetNumber: 'ศธ 04052.12/65/012',
    name: 'เครื่องฉายโปรเจคเตอร์ Epson EB-X06',
    location: 'ห้องพัสดุ (ยืมออก)',
    auditor: 'นางสาวรัตนา สว่างศรี',
    auditDate: '30 ก.ย. 69',
    status: 'pending',
    notes: 'อยู่ระหว่างครูมาลียืมใช้งาน เร่งรัดติดตามคืนเพื่อตรวจสอบ',
  },
];

export const INITIAL_SCHOOL_PROFILE = {
  schoolName: 'โรงเรียนบ้านนิคมสายโท 12 เหนือ',
  schoolCode: '1031260481',
  districtOffice: 'สำนักงานเขตพื้นที่การศึกษาประถมศึกษาบุรีรัมย์ เขต 2',
  subdistrict: 'สายโท 12 เหนือ',
  district: 'บ้านกรวด',
  province: 'บุรีรัมย์',
  postalCode: '31180',
  telephone: '044-601-234',
  email: 'nikomsaito12@buriram2.go.th',
  directorName: 'นายประดิษฐ์ ใจงาม',
  directorPosition: 'ผู้อำนวยการโรงเรียนบ้านนิคมสายโท 12 เหนือ (วิทยฐานะชำนาญการพิเศษ)',
  fiscalYear: 2569,
  totalStudents: 145,
  totalTeachers: 11,
};

export const INITIAL_DEPARTMENTS = [
  {
    id: 'dept-1',
    code: 'วภ-01',
    name: 'กลุ่มบริหารงานวิชาการ',
    headStaffName: 'นายธีรพล สินธุ',
    headStaffPosition: 'ครู ชำนาญการพิเศษ',
    staffCount: 4,
    description: 'รับผิดชอบงานพัฒนาหลักสูตร การจัดการเรียนการสอน วัดผลประเมินผล สื่อการเรียนรู้ และประกันคุณภาพภายใน',
  },
  {
    id: 'dept-2',
    code: 'วภ-02',
    name: 'กลุ่มบริหารงานงบประมาณ แผนงาน และพัสดุ',
    headStaffName: 'นายทัศน์พล เจริญสุข',
    headStaffPosition: 'ครู ชำนาญการพิเศษ (หัวหน้างานพัสดุ)',
    staffCount: 3,
    description: 'รับผิดชอบแผนปฏิบัติการประจำปี การจัดซื้อจัดจ้าง ว.804 ว.119 การเงินบัญชี และการคุมทะเบียนทรัพย์สิน',
  },
  {
    id: 'dept-3',
    code: 'วภ-03',
    name: 'กลุ่มบริหารงานบุคคล',
    headStaffName: 'นายสมศักดิ์ มุ่งมั่น',
    headStaffPosition: 'ครู ชำนาญการ',
    staffCount: 2,
    description: 'รับผิดชอบอัตรากำลัง วินัย การประเมินผลปฏิบัติราชการ การพัฒนาครูและสิทธิประโยชน์',
  },
  {
    id: 'dept-4',
    code: 'วภ-04',
    name: 'กลุ่มบริหารงานทั่วไป',
    headStaffName: 'นางสาววิไลวรรณ พรหมมา',
    headStaffPosition: 'ครู คศ.1',
    staffCount: 2,
    description: 'รับผิดชอบอาคารสถานที่ สิ่งแวดล้อม สัมพันธ์ชุมชน ประชาสัมพันธ์ และยานพาหนะ',
  },
];

export const INITIAL_STAFF = [
  {
    id: 'staff-1',
    staffCode: 'ครู-001',
    title: 'นาย',
    fullName: 'ประดิษฐ์ ใจงาม',
    position: 'ผู้อำนวยการโรงเรียน',
    academicStanding: 'วิทยฐานะชำนาญการพิเศษ',
    departmentId: 'dept-3',
    departmentName: 'ฝ่ายบริหาร / บริหารงานบุคคล',
    procurementRole: 'approver' as const,
    phone: '081-234-5678',
    email: 'pradit@nikomsaito.ac.th',
    active: true,
  },
  {
    id: 'staff-2',
    staffCode: 'ครู-002',
    title: 'นาย',
    fullName: 'ทัศน์พล เจริญสุข',
    position: 'ครู / เจ้าหน้าที่พัสดุ',
    academicStanding: 'วิทยฐานะชำนาญการพิเศษ',
    departmentId: 'dept-2',
    departmentName: 'กลุ่มบริหารงานงบประมาณ แผนงาน และพัสดุ',
    procurementRole: 'procurement_officer' as const,
    phone: '089-876-5432',
    email: 'thatphon@nikomsaito.ac.th',
    active: true,
  },
  {
    id: 'staff-3',
    staffCode: 'ครู-003',
    title: 'นางสาว',
    fullName: 'รัตนา สว่างศรี',
    position: 'ครู / เจ้าหน้าที่การเงินและบัญชี',
    academicStanding: 'วิทยฐานะชำนาญการ',
    departmentId: 'dept-2',
    departmentName: 'กลุ่มบริหารงานงบประมาณ แผนงาน และพัสดุ',
    procurementRole: 'finance_officer' as const,
    phone: '087-654-3210',
    email: 'rattana@nikomsaito.ac.th',
    active: true,
  },
  {
    id: 'staff-4',
    staffCode: 'ครู-004',
    title: 'นาย',
    fullName: 'ธีรพล สินธุ',
    position: 'ครู / หัวหน้าฝ่ายวิชาการ',
    academicStanding: 'วิทยฐานะชำนาญการพิเศษ',
    departmentId: 'dept-1',
    departmentName: 'กลุ่มบริหารงานวิชาการ',
    procurementRole: 'inspector' as const,
    phone: '086-111-2233',
    email: 'theerapol@nikomsaito.ac.th',
    active: true,
  },
  {
    id: 'staff-5',
    staffCode: 'ครู-005',
    title: 'นาย',
    fullName: 'สมศักดิ์ มุ่งมั่น',
    position: 'ครู / หัวหน้างานอาคารสถานที่',
    academicStanding: 'วิทยฐานะชำนาญการ',
    departmentId: 'dept-4',
    departmentName: 'กลุ่มบริหารงานทั่วไป',
    procurementRole: 'inspector' as const,
    phone: '084-555-6677',
    email: 'somsak@nikomsaito.ac.th',
    active: true,
  },
  {
    id: 'staff-6',
    staffCode: 'ครู-006',
    title: 'นาง',
    fullName: 'มาลี ตั้งใจ',
    position: 'ครู / หัวหน้าสายชั้นปฐมวัย',
    academicStanding: 'วิทยฐานะชำนาญการ',
    departmentId: 'dept-1',
    departmentName: 'กลุ่มบริหารงานวิชาการ (ปฐมวัย)',
    procurementRole: 'teacher' as const,
    phone: '081-987-6543',
    email: 'malee@nikomsaito.ac.th',
    active: true,
  },
  {
    id: 'staff-7',
    staffCode: 'ครู-007',
    title: 'นางสาว',
    fullName: 'วิไลวรรณ พรหมมา',
    position: 'ครู / งานประชาสัมพันธ์และกิจกรรมวันสำคัญ',
    academicStanding: 'ครู คศ.1',
    departmentId: 'dept-4',
    departmentName: 'กลุ่มบริหารงานทั่วไป',
    procurementRole: 'inspector' as const,
    phone: '086-456-7890',
    email: 'wilaiwan@nikomsaito.ac.th',
    active: true,
  },
  {
    id: 'staff-8',
    staffCode: 'ครู-008',
    title: 'นาง',
    fullName: 'นันทนา สดใส',
    position: 'ครู / ผู้ดูแลห้องสมุดมีชีวิต',
    academicStanding: 'ครู คศ.1',
    departmentId: 'dept-1',
    departmentName: 'กลุ่มบริหารงานวิชาการ',
    procurementRole: 'teacher' as const,
    phone: '085-333-4455',
    email: 'nantana@nikomsaito.ac.th',
    active: true,
  },
  {
    id: 'staff-9',
    staffCode: 'ครู-009',
    title: 'นาย',
    fullName: 'ชัยรัตน์ ชูชีพ',
    position: 'ครู / งานสุขศึกษา พลศึกษา และโครงการอาหารกลางวัน',
    academicStanding: 'วิทยฐานะชำนาญการ',
    departmentId: 'dept-1',
    departmentName: 'กลุ่มบริหารงานวิชาการ',
    procurementRole: 'teacher' as const,
    phone: '083-999-8877',
    email: 'chairat@nikomsaito.ac.th',
    active: true,
  },
];

export const INITIAL_PROJECTS = [
  {
    id: 'proj-1',
    code: 'โครงการที่ 01/2569',
    name: 'โครงการพัฒนาคุณภาพผู้เรียนและยกระดับผลสัมฤทธิ์ทางการศึกษา',
    strategicIssue: 'ยุทธศาสตร์ที่ 1: พัฒนาคุณภาพและมาตรฐานการศึกษาทุกระดับตามหลักสูตร',
    fiscalYear: 2569,
    departmentId: 'dept-1',
    departmentName: 'กลุ่มบริหารงานวิชาการ',
    ownerStaffId: 'staff-4',
    ownerStaffName: 'นายธีรพล สินธุ',
    ownerPosition: 'ครู ชำนาญการพิเศษ (หัวหน้าฝ่ายวิชาการ)',
    budgetSource: 'เงินอุดหนุนรายหัว (ค่าจัดการเรียนการสอน)',
    totalBudget: 85000,
    spentBudget: 45350,
    status: 'in_progress' as const,
    approvalDate: '1 ต.ค. 2568',
    objectives: [
      'เพื่อยกระดับผลสัมฤทธิ์ทางการเรียนและการประเมินระดับชาติ (O-NET/NT)',
      'เพื่อจัดหาสื่อ วัสดุ และอุปกรณ์การเรียนรู้ที่ทันสมัยสำหรับนักเรียนทุกคน',
    ],
    activities: [
      {
        id: 'act-1-1',
        code: 'กิจกรรมที่ 1.1',
        name: 'กิจกรรมยกระดับผลสัมฤทธิ์ O-NET/NT และติวเข้มวิชาการ',
        responsibleStaffName: 'นายธีรพล สินธุ',
        responsiblePosition: 'ครู ชำนาญการพิเศษ',
        allocatedBudget: 30000,
        spentBudget: 17000,
        status: 'in_progress' as const,
        period: 'ต.ค. 68 - ก.พ. 69',
        description: 'จัดทำเอกสารและสื่อติววิชาคณิตศาสตร์ ภาษาไทย วิทยาศาสตร์ และภาษาอังกฤษ',
      },
      {
        id: 'act-1-2',
        code: 'กิจกรรมที่ 1.2',
        name: 'กิจกรรมจัดซื้อสื่อการสอนและวัสดุอุปกรณ์ห้องปฏิบัติการวิทยาศาสตร์',
        responsibleStaffName: 'นางสาววิไลวรรณ พรหมมา',
        responsiblePosition: 'ครู คศ.1',
        allocatedBudget: 35000,
        spentBudget: 18550,
        status: 'in_progress' as const,
        period: 'พ.ย. 68 - มี.ค. 69',
        description: 'จัดซื้อสารเคมี ชุดทดลอง และแบบจำลองทางวิทยาศาสตร์พื้นฐาน',
      },
      {
        id: 'act-1-3',
        code: 'กิจกรรมที่ 1.3',
        name: 'กิจกรรมส่งเสริมการอ่านและพัฒนาห้องสมุดมีชีวิต',
        responsibleStaffName: 'นางนันทนา สดใส',
        responsiblePosition: 'ครู คศ.1',
        allocatedBudget: 20000,
        spentBudget: 9800,
        status: 'in_progress' as const,
        period: 'ม.ค. 69 - ก.ค. 69',
        description: 'จัดหาหนังสือเสริมความรู้ นิทาน และปรับปรุงชั้นวางหนังสือ',
      },
    ],
  },
  {
    id: 'proj-2',
    code: 'โครงการที่ 02/2569',
    name: 'โครงการจัดซื้อหนังสือเรียนตามนโยบายเรียนฟรี 15 ปีอย่างมีคุณภาพ',
    strategicIssue: 'ยุทธศาสตร์ที่ 2: ขยายโอกาสการเข้าถึงบริการทางการศึกษาอย่างทั่วถึงและมีคุณภาพ',
    fiscalYear: 2569,
    departmentId: 'dept-2',
    departmentName: 'กลุ่มบริหารงานงบประมาณ แผนงาน และพัสดุ',
    ownerStaffId: 'staff-2',
    ownerStaffName: 'นายทัศน์พล เจริญสุข',
    ownerPosition: 'ครู ชำนาญการพิเศษ (หัวหน้างานพัสดุ)',
    budgetSource: 'เงินเรียนฟรี 15 ปี (หมวดหนังสือเรียน)',
    totalBudget: 45000,
    spentBudget: 28350,
    status: 'in_progress' as const,
    approvalDate: '1 ต.ค. 2568',
    objectives: [
      'เพื่อให้นักเรียนทุกคนมีหนังสือเรียนครบ 8 กลุ่มสาระการเรียนรู้ก่อนเปิดภาคเรียน',
      'เพื่อดำเนินการจัดซื้อตามระเบียบพัสดุและคู่มือของกระทรวงศึกษาธิการอย่างโปร่งใส',
    ],
    activities: [
      {
        id: 'act-2-1',
        code: 'กิจกรรมที่ 2.1',
        name: 'คัดเลือกและจัดซื้อหนังสือเรียน 8 กลุ่มสาระ ชั้น ป.1 - ป.6',
        responsibleStaffName: 'นายทัศน์พล เจริญสุข',
        responsiblePosition: 'ครู ชำนาญการพิเศษ',
        allocatedBudget: 38000,
        spentBudget: 28350,
        status: 'in_progress' as const,
        period: 'พ.ค. 69 - ก.ค. 69',
        description: 'จัดทำบัญชียอดนักเรียน สั่งซื้อจากองค์การค้าของ สกสค. และสำนักพิมพ์ที่ผ่านการรับรอง',
      },
      {
        id: 'act-2-2',
        code: 'กิจกรรมที่ 2.2',
        name: 'ตรวจรับหนังสือและแจกจ่ายให้นักเรียนครบ 100%',
        responsibleStaffName: 'นางสาวรัตนา สว่างศรี',
        responsiblePosition: 'ครู ชำนาญการ',
        allocatedBudget: 7000,
        spentBudget: 0,
        status: 'pending' as const,
        period: 'ส.ค. 69 - ก.ย. 69',
        description: 'การลงทะเบียนพัสดุและจัดทำหลักฐานการแจกจ่ายรายบุคคล',
      },
    ],
  },
  {
    id: 'proj-3',
    code: 'โครงการที่ 03/2569',
    name: 'โครงการปรับปรุงซ่อมแซมและพัฒนาสภาพแวดล้อมอาคารสถานที่',
    strategicIssue: 'ยุทธศาสตร์ที่ 3: เสริมสร้างความปลอดภัยและพัฒนาสภาพแวดล้อมให้เอื้อต่อการเรียนรู้',
    fiscalYear: 2569,
    departmentId: 'dept-4',
    departmentName: 'กลุ่มบริหารงานทั่วไป',
    ownerStaffId: 'staff-5',
    ownerStaffName: 'นายสมศักดิ์ มุ่งมั่น',
    ownerPosition: 'ครู ชำนาญการ (หัวหน้างานอาคารสถานที่)',
    budgetSource: 'เงินรายได้สถานศึกษา และเงินอุดหนุน',
    totalBudget: 60000,
    spentBudget: 36800,
    status: 'in_progress' as const,
    approvalDate: '1 ต.ค. 2568',
    objectives: [
      'เพื่อปรับปรุงซ่อมแซมอาคารเรียน ระบบไฟฟ้า และสุขาภิบาลให้ปลอดภัย',
      'เพื่อปรับภูมิทัศน์และระเบียงทางเดินให้สะดวกสำหรับนักเรียนทุกคน',
    ],
    activities: [
      {
        id: 'act-3-1',
        code: 'กิจกรรมที่ 3.1',
        name: 'ซ่อมแซมพื้นระเบียงทางเดินและหลังคาห้องพยาบาล',
        responsibleStaffName: 'นายสมศักดิ์ มุ่งมั่น',
        responsiblePosition: 'ครู ชำนาญการ',
        allocatedBudget: 25000,
        spentBudget: 18500,
        status: 'completed' as const,
        period: 'ก.ค. 69 - ก.ย. 69',
        description: 'เปลี่ยนกระเบื้องหลังคาที่แตก ปูแผ่นกันลื่นทางลาดหน้าห้องพยาบาล',
      },
      {
        id: 'act-3-2',
        code: 'กิจกรรมที่ 3.2',
        name: 'ซ่อมบำรุงระบบระบายน้ำและสุขาภิบาลรอบอาคาร 1',
        responsibleStaffName: 'นายสมศักดิ์ มุ่งมั่น',
        responsiblePosition: 'ครู ชำนาญการ',
        allocatedBudget: 15000,
        spentBudget: 4500,
        status: 'completed' as const,
        period: 'ส.ค. 69 - ก.ย. 69',
        description: 'ลอกรางระบายน้ำและล้างบ่อพักน้ำทิ้ง',
      },
      {
        id: 'act-3-3',
        code: 'กิจกรรมที่ 3.3',
        name: 'ปรับปรุงทาสีห้องสมุดมีชีวิตและซ่อมชั้นวางหนังสือ',
        responsibleStaffName: 'นายสมศักดิ์ มุ่งมั่น',
        responsiblePosition: 'ครู ชำนาญการ',
        allocatedBudget: 20000,
        spentBudget: 13800,
        status: 'in_progress' as const,
        period: 'ส.ค. 69 - ต.ค. 69',
        description: 'ทาสีภายในห้องสมุดและซ่อมชั้นวางหนังสือ',
      },
    ],
  },
  {
    id: 'proj-4',
    code: 'โครงการที่ 04/2569',
    name: 'โครงการส่งเสริมสุขภาวะ โภชนาการ และการกีฬาในสถานศึกษา',
    strategicIssue: 'ยุทธศาสตร์ที่ 4: พัฒนาผู้เรียนให้มีสุขภาวะทางกายและจิตใจที่ดี',
    fiscalYear: 2569,
    departmentId: 'dept-1',
    departmentName: 'กลุ่มบริหารงานวิชาการ',
    ownerStaffId: 'staff-9',
    ownerStaffName: 'นายชัยรัตน์ ชูชีพ',
    ownerPosition: 'ครู ชำนาญการ',
    budgetSource: 'เงินอุดหนุนกิจกรรมพัฒนาคุณภาพผู้เรียน',
    totalBudget: 35000,
    spentBudget: 14150,
    status: 'in_progress' as const,
    approvalDate: '1 ต.ค. 2568',
    objectives: [
      'เพื่อให้นักเรียนมีอุปกรณ์กีฬาเพียงพอในการฝึกซ้อมและแข่งขัน',
      'เพื่อส่งเสริมการปลูกผักเกษตรอินทรีย์สนับสนุนอาหารกลางวันของนักเรียน',
    ],
    activities: [
      {
        id: 'act-4-1',
        code: 'กิจกรรมที่ 4.1',
        name: 'จัดซื้ออุปกรณ์กีฬาและแข่งขันกีฬากลุ่มโรงเรียน',
        responsibleStaffName: 'นายชัยรัตน์ ชูชีพ',
        responsiblePosition: 'ครู ชำนาญการ',
        allocatedBudget: 20000,
        spentBudget: 12000,
        status: 'completed' as const,
        period: 'ก.ค. 69 - ก.ย. 69',
        description: 'ซื้อลูกฟุตบอล วอลเลย์บอล ตะกร้อ และอุปกรณ์ฝึกซ้อม',
      },
      {
        id: 'act-4-2',
        code: 'กิจกรรมที่ 4.2',
        name: 'โครงการแปลงผักเกษตรเพื่ออาหารกลางวัน',
        responsibleStaffName: 'นายชัยรัตน์ ชูชีพ',
        responsiblePosition: 'ครู ชำนาญการ',
        allocatedBudget: 15000,
        spentBudget: 2150,
        status: 'in_progress' as const,
        period: 'ส.ค. 69 - ธ.ค. 69',
        description: 'จัดซื้อดินปลูก ปุ๋ยชีวภาพ และเมล็ดพันธุ์ผักสวนครัว',
      },
    ],
  },
  {
    id: 'proj-5',
    code: 'โครงการที่ 05/2569',
    name: 'โครงการส่งเสริมคุณธรรม จริยธรรม และกิจกรรมวันสำคัญ',
    strategicIssue: 'ยุทธศาสตร์ที่ 5: ปลูกฝังค่านิยม ประชาธิปไตย และความเป็นไทย',
    fiscalYear: 2569,
    departmentId: 'dept-4',
    departmentName: 'กลุ่มบริหารงานทั่วไป',
    ownerStaffId: 'staff-7',
    ownerStaffName: 'นางสาววิไลวรรณ พรหมมา',
    ownerPosition: 'ครู คศ.1',
    budgetSource: 'เงินอุดหนุนรายหัว',
    totalBudget: 20000,
    spentBudget: 2375,
    status: 'in_progress' as const,
    approvalDate: '1 ต.ค. 2568',
    objectives: [
      'เพื่อให้นักเรียนได้ร่วมกิจกรรมวันสำคัญทางชาติ ศาสนา และพระมหากษัตริย์',
      'เพื่อปลูกฝังความกตัญญูกตเวทีและจิตอาสาเพื่อสังคม',
    ],
    activities: [
      {
        id: 'act-5-1',
        code: 'กิจกรรมที่ 5.1',
        name: 'กิจกรรมจัดงานวันสำคัญทางศาสนา วันแม่ และวันพ่อแห่งชาติ',
        responsibleStaffName: 'นางสาววิไลวรรณ พรหมมา',
        responsiblePosition: 'ครู คศ.1',
        allocatedBudget: 12000,
        spentBudget: 2375,
        status: 'in_progress' as const,
        period: 'ต.ค. 68 - ก.ย. 69',
        description: 'จัดหาผ้าประดับ ดอกไม้สด และอุปกรณ์ประกอบพิธีการ',
      },
      {
        id: 'act-5-2',
        code: 'กิจกรรมที่ 5.2',
        name: 'กิจกรรมค่ายคุณธรรมและความเป็นพลเมืองดี',
        responsibleStaffName: 'นางสาววิไลวรรณ พรหมมา',
        responsiblePosition: 'ครู คศ.1',
        allocatedBudget: 8000,
        spentBudget: 0,
        status: 'pending' as const,
        period: 'ม.ค. 69 - ก.พ. 69',
        description: 'กิจกรรมส่งเสริมระเบียบวินัยและจิตสาธารณะ',
      },
    ],
  },
];
